### ISSUE TITLE
Always Incognito mode

### ISSUE THREAD

**Issue by cyanlemons** [GrapheneOS/Vanadium#65] opened 2020-05-17 20:31 UTC
Although one can specifically open an incognito tab, it would be nice if there was an option in Vanadium for an "Always Incognito" mode, similar to the "Always use private browsing mode" option in Firefox. That way, when opening links from other apps, it would always default to an incognito tab – same for the default tab when opening Vanadium after fully closing the app.

**Comment by cyanlemons** [comment] 2020-12-23 17:16
It seems there is already a way to do this via the [IncognitoModeAvailability](https://cloud.google.com/docs/chrome-enterprise/policies/?policy=IncognitoModeAvailability) policy. However, it currently says:
> Note that 'Forced' does not work for Android-on-Chrome

I've [found the assert](https://github.com/chromium/chromium/blob/99314be8152e688bafbbf9a615536bdbb289ea87/chrome/browser/profiles/incognito_utils_android.cc#L18) where it verifies that this is the case, but I wonder how functional it would be if this assert was simply removed. Perhaps there are only a few patches to make before it can be supported on Android.

**Comment by MaxHillebrand** [comment] 2022-03-11 17:17
This is a very useful feature, especially for links from other apps, but also for the search widget.

An additional feature request is to turn incognito tabs into persistent tabs, in the case they want to be stored for later reference.

**Comment by caveman1973** [comment] 2022-05-13 08:58
Duckduckgo browser has a great implementation; All browsing data is deleted after closing (or after a set data interval).

When you want to keep cookies and data from a website you visit, you click in the options tab to "fireproof" the website. It's a 2 click process.

**Comment by Zanthed** [comment] 2022-05-13 14:07
That isn't relevant because DuckDuckGo Browser is not a browser. It's just a WebView in the form of a browser. There's nothing for us to use.

**Comment by thestinger** [comment] 2022-05-13 16:04
Deleting data after the fact is much different than always incognito which would avoid persisting the data.

**Comment by caveman1973** [comment] 2022-05-14 21:16
If you allow exceptions, will the cookies persist? There's just a few websites i would prefer to keep cookies so I don't have to type credentials to log in.

**Comment by Zanthed** [comment] 2022-05-14 21:40
No, that would have to be implemented. And it's still different than Always Incognito mode because you're now allowing data to persist.

**Comment by thestinger** [comment] 2022-05-14 21:50
@caveman1973 Perhaps what you want is Incognito by default with the ability to still manually open a site in non-Incognito.

**Comment by thestinger** [comment] 2022-05-14 21:50
Support for wiping cookies other than certain exceptions is something Chromium is likely to implement themselves and isn't really comparable to this feature.

**Comment by caveman1973** [comment] 2022-05-15 02:02
> @caveman1973 Perhaps what you want is Incognito by default with the ability to still manually open a site in non-Incognito.

Exactly. I don't like the hassle of having to manually clean cookies and browse history. So always incognito seems the way to go. 

But for the very few websites I visit often (like this one, GitHub), I don't want to enter the login details every time, so I would like to make the exception (only cookies, not third-party). 

That way I know there's no persistent data for 99% of my browsing. And I don't have to worry about open an incognito tab.

**Closed** 2022-07-07 13:24 UTC
Labels: enhancement

**Comment by Broeckelmann** [comment] 2022-09-29 18:14
@thestinger 
What's the status of this issue? 
Is this going to be implemented?🤔

**Comment by thestinger** [comment] 2022-09-29 18:25
There's a toggle for opening links in Incognito. You can see the issue is closed as completed. Stop pinging developers unnecessarily.
