### ISSUE TITLE
[Feature Request] Implement Always Incognito Mode from Bromite

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/Vanadium#291] opened 2023-03-19 04:14 UTC
A very useful feature.

https://github.com/bromite/bromite/blob/master/build/patches/Add-an-always-incognito-mode.patch

**Comment by r3g-5z** [comment] 2023-03-19 04:16
Duplicate of https://github.com/GrapheneOS/Vanadium/issues/65

Already implemented in https://github.com/GrapheneOS/Vanadium/blob/main/patches/0084-Toggle-for-navigating-external-URL-in-incognito.patch and https://github.com/GrapheneOS/Vanadium/blob/main/patches/0087-Support-opening-external-web-search-in-incognito.patch

**Closed by r3g-5z** 2023-03-19 04:16 UTC

**Comment by thestinger** [comment] 2023-03-19 04:32
@russianbot91 You were previously asked to stop doing this. Bromite is GPLv3 and the patches cannot be legally used by GrapheneOS even if we wanted to use their approach to these features, which we don't.
