### ISSUE TITLE
bundletool error

### ISSUE THREAD

**Issue by the-good-stuff** [GrapheneOS/Vanadium#70] opened 2020-07-21 00:55 UTC
Hello,
I'm trying to build latest Vanadium but I get an error on the generate_release script. It seems related to bundletool: error: failed to deserialize resources.pb: duplicate configuration in resource table. 
[bundletool.txt](https://github.com/GrapheneOS/Vanadium/files/4950663/bundletool.txt)
I made a fresh vm with Ubuntu 20.04 and tested there, and same issue. Am I missing anything?

**Comment by thestinger** [comment] 2020-07-21 03:02
This is an upstream issue. You'll need to build the version from the stable release if you don't want to help debug it.

**Comment by the-good-stuff** [comment] 2020-07-21 04:06
I tried building 84.0.4147.89. I followed the instructions from here: https://grapheneos.org/build#browser-and-webview
Where do I find the logs for this error?

**Comment by thestinger** [comment] 2020-07-21 04:22
If you don't want to help debug this upstream issue, build the version of Vanadium from the last GrapheneOS stable release.

**Comment by the-good-stuff** [comment] 2020-07-21 04:24
ah, ok. 
will try to look into it maybe I figure it out. I tried different versions of bundletool but that isn't the issue.

**Comment by thestinger** [comment] 2020-07-21 04:25
The issue isn't bundletool. The error occurs in aapt2 when it finds a duplicate resource of some kind.

**Comment by thestinger** [comment] 2020-07-21 16:51
This was resolved by adding an apk target to avoid whatever goes wrong generating the resources for the bundle with aapt2.

**Closed by thestinger** 2020-07-21 16:51 UTC
Labels: bug, upstream
