### ISSUE TITLE
Merge Bromite patch to allow moving address bar to bottom

### ISSUE THREAD

**Issue by chriswoope** [GrapheneOS/Vanadium#174] opened 2022-04-24 10:07 UTC
Bromite has support for moving the address bar to the bottom, where it's easier to reach when holding the phone with one hand.

It would be nice to have it in Vanadium, and it should be really easy to add by just importing the Bromite patch at https://github.com/bromite/bromite/blob/master/build/patches/Move-navigation-bar-to-bottom.patch

**Comment by Zanthed** [comment] 2022-04-24 17:18
We cannot use their patches 1-1 because Bromite's patches are GPLv3 licenced. Patches from other projects are not 1-1 to our codebase and you can't just simply drop them in. They need to be changed and adapted to our codebase. Someone needs to maintain these patches each Chromium update.

and duplicate of https://github.com/GrapheneOS/Vanadium/issues/110

I suggest you star this Chromium issue to let the developers know this is a feature people want. https://bugs.chromium.org/p/chromium/issues/detail?id=1284380

**Closed by Zanthed** 2022-04-24 17:18 UTC

**Comment by uazo** [comment] 2022-04-26 07:27
allow me, I answer here the request in https://github.com/uazo/bromite/pull/19

> We cannot use their patches 1-1 because Bromite's patches are GPLv3 licenced.

from my point of view there is absolutely no problem.
if @csagan5 also agrees for me it is ok

**Comment by csagan5** [comment] 2022-04-26 16:05
> from my point of view there is absolutely no problem.

Anecdotally nobody understands the difference between licenses until a non-GPL patch is included in a paid-for app, possibly with other user-hostile changes, and/or possibly sues the original author for copyright infringement; these are some of the reasons why Bromite uses GPLv3: it would allow involving [FSF](https://www.fsf.org/) in case of some major screw-up.

> if @csagan5 also agrees for me it is ok

You are the author so you would be re-licensing it with another license, I have no say in the matter.

**Comment by uazo** [comment] 2022-04-27 07:14
@csagan5 thanks for the suggestions, I really know nothing about opensource licenses, I never bothered to check it, my fault.
so with MIT that code is no longer obliged to be opened? then I'm sorry I wasted your time, but I think that my works (when it's really my job, like in this case) will remain under the GPL.
I hope that the vanadium team can find a possible alternative to this issue

**Comment by chriswoope** [comment] 2022-04-28 02:12
Could making Vanadium as a whole GPLv3 be reasonable given that it would allow to merge code from Bromite and that overall the GPLv3 protects against a bunch of things that don't seem very desirable like someone releasing a proprietary derivative or shipping Vanadium in a device with a non-unlockable bootloader?

Alternatively, if there is the desire to also release code under the MIT license (because their authors want it that way or perhaps to allow upstream or other forks to pick it up automatically), one could make a "Mitadium" project and have Vanadium be a fork of "Mitadium" with the addition of GPL licensed code.

**Comment by Zanthed** [comment] 2022-04-28 03:17
We're not going to make Vanadium GPLv3 because it goes directly against our entire purpose of using MIT which is to allow other companies to use GrapheneOS, create their own locked down devices, etc.

**Comment by Zanthed** [comment] 2022-04-28 03:18
See https://grapheneos.org/faq#bundled-apps

**Comment by Zanthed** [comment] 2022-04-28 03:19
We're also not going to put in the resources to create *and* maintain two versions of the browser. Creating it is one thing. Maintaining is something people forget about way too much. Yes we can do so many things but who is going to maintain that? We have far higher priority things.

**Comment by csagan5** [comment] 2022-04-28 22:23
> thanks for the suggestions, I really know nothing about opensource licenses, I never bothered to check it, my fault.

Please, do not take advice from me on this; I made my mind long time ago after some awful despicable public incidents ([1](https://sfconservancy.org/blog/2021/jul/23/tivoization-and-the-gpl-right-to-install/), [2](https://en.wikipedia.org/wiki/Open_source_license_litigation) and less famous ones where I was more directly involved; you will anyways find plenty every few months in the [news](https://blog.opensource.org/gnome-patent-troll-stripped-of-patent-rights/)). GPLv3 is not a "cure" for all evils but supposedly should allow a bit more ground on specific issues (the fact that binary distributions must comply with on-demand source code releases is the main strength).

You should also read about the criticism to GPL licenses (and which parties benefit most from the different types of licenses).

> so with MIT that code is no longer obliged to be opened?

Yes, this is a simple explanation: https://softwareengineering.stackexchange.com/a/318108

**Comment by thestinger** [comment] 2022-04-28 22:39
@chriswoope GPLv3, AGPLv3 and LGPLv3 are forbidden for inclusion in GrapheneOS. They forbid use cases for GrapheneOS which are important to support to advance the goals of improving privacy and security throughout the industry including in locked down embedded / mobile devices. It needs to be allowed to make a device based on GrapheneOS with an immutable root of trust, which can be important for high security use cases. It's entirely possible for a vendor to sell both unlockable and immutable root of trust variants of a device with the user choosing which they want to purchase. It isn't inherently anti-user to have an immutable root of trust. We consider those licenses non-free like OpenBSD does and won't include anything using them. GPLv2 / LGPLv2 is acceptable for existing code but we won't include new GPLv2 / LGPLv2 code if at all possible especially since it's an indication the project may become GPLv3 if it's not GPLv2-only with far too many copyright owners to ever relicense the project which is the case for the Linux kernel.

Vanadium is included in the OS and cannot use any GPLv3 code. Including GrapheneOS code in a GPLv3 project is comparable to including it in a closed source one from our perspective since either way we're unable to take anything back from that project. We're fine with both closed source and GPLv3 projects using our code but it's worth bearing in mind that it's a comparably one way relationship either way. Either way, they can submit some of their changes to us with permissive licensing. There isn't really much difference from our perspective.

We contributed to FlorisBoard with the hope of being able to include it in GrapheneOS to replace AOSP Keyboard but that's now cancelled due to them using a LGPLv3 spell checking library. We won't be contributing to it again unless there's a plan to replace that library, and if we wanted to use it we'd have to work on replacing the library.

**Comment by thestinger** [comment] 2022-06-15 16:06
We can develop replacements for everything we want ourselves. We can collaborate with upstream or another project willing to work with us and not participating in attacks on the GrapheneOS project and developers.
